// Code generated by MockGen. DO NOT EDIT.
// Source: dump.go
//
// Generated by this command:
//
//	mockgen -source dump.go -package=mock -destination=mock/dump.go
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dump "github.com/ozontech/ch-rollup/pkg/dump"
	gomock "go.uber.org/mock/gomock"
)

// MockDumper is a mock of Dumper interface.
type MockDumper struct {
	ctrl     *gomock.Controller
	recorder *MockDumperMockRecorder
}

// MockDumperMockRecorder is the mock recorder for MockDumper.
type MockDumperMockRecorder struct {
	mock *MockDumper
}

// NewMockDumper creates a new mock instance.
func NewMockDumper(ctrl *gomock.Controller) *MockDumper {
	mock := &MockDumper{ctrl: ctrl}
	mock.recorder = &MockDumperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDumper) EXPECT() *MockDumperMockRecorder {
	return m.recorder
}

// Dump mocks base method.
func (m *MockDumper) Dump(id, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dump", id, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dump indicates an expected call of Dump.
func (mr *MockDumperMockRecorder) Dump(id, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dump", reflect.TypeOf((*MockDumper)(nil).Dump), id, content)
}

// Listen mocks base method.
func (m *MockDumper) Listen(sender dump.Sender, interval int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Listen", sender, interval)
}

// Listen indicates an expected call of Listen.
func (mr *MockDumperMockRecorder) Listen(sender, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockDumper)(nil).Listen), sender, interval)
}

// ProcessNext mocks base method.
func (m *MockDumper) ProcessNext(sender dump.Sender) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNext", sender)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNext indicates an expected call of ProcessNext.
func (mr *MockDumperMockRecorder) ProcessNext(sender any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNext", reflect.TypeOf((*MockDumper)(nil).ProcessNext), sender)
}
